[build]
builder = "go"
buildCommand = "go build -o server ./cmd/api"

[deploy]
startCommand = "./server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
